project: CMIP6
mip: CMIP

models:
- CNRM-CM6-1
- CNRM-ESM2-1

experiments:
  - historical
  - piControl

members:
  - r1i1p1f2
  - r2i1p1f2

variables:
  - variable: tas
    table: Amon
  - variable: pr
    table: Amon

thredds:
  catalog_url: https://thredds-su.ipsl.fr/thredds/catalog/CNRM-WCRP-Data/CMIP6/catalog.xml
  #catalog_url: https://thredds-su.ipsl.fr/thredds/catalog/CNRM-WCRP-Data/CMIP6/CMIP/CNRM-CERFACS/CNRM-ESM2-1/historical/r1i1p1f2/catalog.xml
  http_base: https://thredds-su.ipsl.fr/thredds/fileServer/

output:
  wget_script: download_cmip6.sh
